"""initial_schema

Revision ID: 2865c48fe099
Revises: 
Create Date: 2026-08-19 16:59:38.096460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2865c48fe099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_bibles',
    sa.Column('novel_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('bible_revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('import_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('novel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('added_chapters', sa.Integer(), nullable=False),
    sa.Column('skipped_chapters', sa.Integer(), nullable=False),
    sa.Column('updated_chapters', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_import_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('novels',
    sa.Column('novel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_r2_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('translated_chapters', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('novel_id')
    )
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.create_index('idx_novels_updated_at', ['updated_at'], unique=False)

    op.create_table('profile_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('min_independent_sources', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('novel_id', sa.String(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('translated_file_path', sa.String(), nullable=True),
    sa.Column('r2_url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_translation_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('chapters',
    sa.Column('novel_id', sa.String(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('chapter_title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('original_text_preview', sa.Text(), nullable=False),
    sa.Column('translated_text_preview', sa.Text(), nullable=False),
    sa.Column('original_r2_key', sa.String(), nullable=True),
    sa.Column('translated_r2_key', sa.String(), nullable=True),
    sa.Column('translated_r2_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('novel_id', 'chapter_index')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('idx_chapters_novel_chapter_id', ['novel_id', 'chapter_id'], unique=True)

    op.create_table('profile_books',
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('novel_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('title_key', sa.String(), nullable=False),
    sa.Column('author_key', sa.String(), nullable=False),
    sa.Column('sampled_chapters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('book_id')
    )
    with op.batch_alter_table('profile_books', schema=None) as batch_op:
        batch_op.create_index('idx_profile_books_title_author_key', ['title_key', 'author_key'], unique=False)

    op.create_table('profile_editions',
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fingerprints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('mapping_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['profile_books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edition_id')
    )
    with op.batch_alter_table('profile_editions', schema=None) as batch_op:
        batch_op.create_index('idx_profile_editions_book_id', ['book_id'], unique=False)

    op.create_table('profile_chapter_mappings',
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('local_chapter_index', sa.Integer(), nullable=False),
    sa.Column('canonical_chapter_start', sa.Integer(), nullable=False),
    sa.Column('canonical_chapter_end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mapping_revision', sa.Integer(), nullable=False),
    sa.CheckConstraint('canonical_chapter_end >= canonical_chapter_start', name='chk_mapping_canonical_range'),
    sa.ForeignKeyConstraint(['edition_id'], ['profile_editions.edition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edition_id', 'local_chapter_index')
    )
    op.create_table('profile_submissions',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('local_chapter_start', sa.Integer(), nullable=False),
    sa.Column('local_chapter_end', sa.Integer(), nullable=False),
    sa.Column('canonical_chapter_start', sa.Integer(), nullable=False),
    sa.Column('canonical_chapter_end', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('chapter_fingerprint', sa.String(), nullable=False),
    sa.Column('source_group_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['profile_books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edition_id'], ['profile_editions.edition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('profile_submissions', schema=None) as batch_op:
        batch_op.create_index('idx_profile_submissions_book_id', ['book_id'], unique=False)
        batch_op.create_index('idx_profile_submissions_edition_id', ['edition_id'], unique=False)

    op.create_table('profile_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('character_original_name', sa.String(), nullable=False),
    sa.Column('canonical_chapter', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('attribute_key', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('certainty', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_group_id', sa.String(), nullable=False),
    sa.Column('source_submission_id', sa.String(), nullable=False),
    sa.Column('supersedes_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['profile_books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_submission_id'], ['profile_submissions.submission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['profile_events.event_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_key')
    )
    with op.batch_alter_table('profile_events', schema=None) as batch_op:
        batch_op.create_index('idx_profile_events_book_char_chapter', ['book_id', 'character_id', 'canonical_chapter'], unique=False)
        batch_op.create_index('idx_profile_events_book_status_chapter', ['book_id', 'status', 'canonical_chapter'], unique=False)
        batch_op.create_index('idx_profile_events_source_submission', ['source_submission_id'], unique=False)

    op.create_table('profile_evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('source_group_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['profile_events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['profile_submissions.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('event_id', 'source_group_id', 'submission_id', name='uq_profile_evidence_unique_entry')
    )
    with op.batch_alter_table('profile_evidence', schema=None) as batch_op:
        batch_op.create_index('idx_profile_evidence_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_evidence', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_evidence_event_id')

    op.drop_table('profile_evidence')
    with op.batch_alter_table('profile_events', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_events_source_submission')
        batch_op.drop_index('idx_profile_events_book_status_chapter')
        batch_op.drop_index('idx_profile_events_book_char_chapter')

    op.drop_table('profile_events')
    with op.batch_alter_table('profile_submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_submissions_edition_id')
        batch_op.drop_index('idx_profile_submissions_book_id')

    op.drop_table('profile_submissions')
    op.drop_table('profile_chapter_mappings')
    with op.batch_alter_table('profile_editions', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_editions_book_id')

    op.drop_table('profile_editions')
    with op.batch_alter_table('profile_books', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_books_title_author_key')

    op.drop_table('profile_books')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('idx_chapters_novel_chapter_id')

    op.drop_table('chapters')
    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_translation_jobs_status_created')

    op.drop_table('translation_jobs')
    op.drop_table('profile_settings')
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_index('idx_novels_updated_at')

    op.drop_table('novels')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_import_jobs_status_created')

    op.drop_table('import_jobs')
    op.drop_table('book_bibles')
    # ### end Alembic commands ###
