from .templates import (
    PROMPT_1_EXTRACT_BOOK_BIBLE_DELTA,
    PROMPT_2_TRANSLATE_CHUNK_SYSTEM,
    PROMPT_2_TRANSLATE_CHUNK_USER,
    PROMPT_3_TRANSLATE_HTML_SYSTEM,
    PROMPT_3_TRANSLATE_HTML_USER,
    PROMPT_4_QA_CHECK
)

__all__ = [
    "PROMPT_1_EXTRACT_BOOK_BIBLE_DELTA",
    "PROMPT_2_TRANSLATE_CHUNK_SYSTEM",
    "PROMPT_2_TRANSLATE_CHUNK_USER",
    "PROMPT_3_TRANSLATE_HTML_SYSTEM",
    "PROMPT_3_TRANSLATE_HTML_USER",
    "PROMPT_4_QA_CHECK",
]
