from typing import Any, Dict, List, Optional, Protocol


class BlobStore(Protocol):
    def put_bytes(self, object_name: str, data: bytes, content_type: str = "application/octet-stream") -> Optional[str]: ...

    def get_bytes(self, object_name: str, raise_on_error: bool = False) -> Optional[bytes]: ...

    def delete_file(self, object_name: str) -> bool: ...


class JobStore(Protocol):
    def save_job(self, job: Any) -> None: ...

    def get_job(self, job_id: str) -> Optional[Any]: ...

    def list_jobs(self) -> List[Any]: ...


class BibleStore(Protocol):
    def get_bible(self, novel_id: str) -> Optional[Any]: ...

    def save_bible(self, novel_id: str, bible: Any) -> None: ...

    def merge_bible_delta(self, novel_id: str, delta: Any, **kwargs) -> Any: ...

    def delete_bible(self, novel_id: str) -> bool: ...
